### ISSUE TITLE
Script leaves artifacts of unused framework

### ISSUE THREAD

**Issue by timhaywood** [hyperbrew/create-bolt-cep#2]
## Issue

The setup script leaves a few artifacts of unusused framework, such as:

- [Leaving the Vite plugin (and import) of the unused framework](https://github.com/hyperbrew/bolt-cep/blob/46a7bc6e552e7a7c67f92729c3975c0d50790bc6/vite.config.ts#L32):

    ```ts
    export default defineConfig({
      plugins: [
        react(),
        vue(),
    ```
- Not setting the correct `tsconfig.json` (doesn't rename `tsconfig.jsonreact`)
- Doesn't remove unused packages from `package.json`

This isn't a big deal, since they're all pretty easy to change yourself. So no problem to leave as is for the moment I think.

## Possible solutions

Have been thinking about if there was any ways to improve the experience, and so far these are what I'd come up with. Have looked at how a few other projects do it, but will continue to do a bit more research.

### Handle via the create script

First solution is to add to the current create script in this repo, which is definetly doable.

The downside to this is the create script becomes very closely linked to the imeplementation in the template repo, and any extra framework specific code will need to be addressed in the create script.

### Split templates at a higher level

The more common solution would be to split the templates at a higher level, so each template has it's own complete project folder including `package.json`.

**Advantages**
- No coupling between the template and the create script, so it's easy to make adjustments to each template
- Simpler create script
- Easy to add new templates with significant differences

**Disadvantages**
- Requires significant refactor of current system
- Increase in duplicate code between templates (address this below)

### Reducing duplication

To reduce duplication between the templates, I think it might be beneficial to add some more abstractions into the package.

For example, abstracting the default vite extendscript config into the `vite-cep-plugin` package. Any changes to the extendscript config could be done in the `cep.config.ts`?

```ts
// vite.config.ts

import { cep, extendscriptConfig } from "vite-cep-plugin";
import cepConfig from "./cep.config";

// ...

extendscriptConfig(
  `src/jsx/index.ts`,
  outPathExtendscript,
  cepConfig,
  extensions,
  isProduction,
  isPackage
);
```

I don't think users will be changing the config much at all, and this allows it to be updated via npm if you make any changes to it.

<details>

<summary>Other ideas</summary>

It might be nice to have the cep config created by a function, so you could provide some defaults as well as the expected type.

```ts
// cep.config.ts
import { createConfig } from "vite-cep-plugin";
import { version } from "./package.json";

// Provides defaults, but merges in
// provided object
const config = createConfig({
  version,
  id: "com.bolt.cep",
  displayName: "Bolt CEP",
  zxp: {
    country: "US",
    province: "CA",
    org: "MyCompany",
    password: "mypassword",
  },
});

export default config;
```

</details>

### Monorepo

Related to this, personally I find a monorepo structure easier to maintain, e.g.

```md
bolt-cep repo
- templates
    - react
    - vue
- packages
    - create-bolt-cep
    - vite-cep-plugin
- README.md
```

Since you can make changes that affect multiple templates, packages, and you can release new versions of multiple packages at once easily.

## Contributing

Sorry this ended up being super long! Have been using `bolt-cep` a lot and it's been amazing, so have been thinking about it! More than happy to do PRs for any proposed changes, keen to start a discussion and hear your thoughts.

**Comment by justintaylor-dev** [comment]
@timhaywood sorry for the silence, just wanted to say thanks for the suggestions, many of these are on the roadmap and some are really great solutions to the issues.

**Templates**
I do need cleaner way to separate these, while still being able to test bolt in the repo without generating a new extension each time. Since they share a lot of assets (JSX mostly) I don't know if totally separate folders make sense as there will be a lot of redundancy, but I do think separate `Vite` configs and `package.json` s is a good approach. So basically, thanks for those suggestions, I will be streamlining that process when I get a chance and before releasing the Svelte implementation.

**Functions / Actions**
I did introduce functions recently with `yarn symlink` and `yarn delsymlink` for quick creating and deleting symlinks. I may be adding more of these for CEP specific functions, but regarding config I'd like to keep that separate for now as it's useful for also importing into your project in certain situations, like grabbing your panel ID for the ns and version and what not.

**Monorepo**
I do really like this idea, at least for the create script, will take some reworking but will definitely investigate. Thanks for the suggestion!

Will keep you posted on changes. Thanks!

**Comment by timhaywood** [comment]
No worries, thanks for taking the time to read through it all! Appreciate the thought out response.

Excited to continue to watch the project grow and improve! Let me know if you'd appreciate contributions on anything specific :)

**Comment by justintaylor-dev** [comment]
@timhaywood to follow up on some of these points:

The main template now contains unique files per framework for:

- `package.json`
- `vite.config.ts`
- `tsconfig.json`

The others get excluded upon creation, so there aren't any artifacts or un-necessary dependencies left.

**Comment by timhaywood** [comment]
Yeah perfect, thanks for that!
